repos:
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.76.1
    hooks:
      - id: cfn-lint-rc
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
